#gcloud compute disks create gke-pv --zone=us-central1-c --size=5GB  <--- to create the disk in gcp
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: manual-disk-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce #ReadWriteMany not applicable to PD, and Mapped to a specific Node. 
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: default
    name: manual-disk-pvc
  gcePersistentDisk:
    pdName: gke-pv
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: manual-disk-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi