- name: Installing webserver app based on OS
  hosts: testservers
  remote_user: root 

  tasks:
  - name: Installing nginx on Ubuntu
    apt:
      name: nginx
      state: present 
    when: ansible_os_family == "Debian"
  
  - name: Installing apache on RedHat 
    yum:
      name: apache2
      state: present 
    when: ansible_os_family == "RedHat"
  
  - name: Installing IIS on Windows
    win_feature:
      name: 
      - Web-Server
      - Web-Common-Http
      state: present
    when: ansible_os_family == "Windows"