apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-cross-ns-comm
  namespace: dev-team
spec:
  podSelector:
    matchLabels:
      name: nginx-pod
  policyTypes:
  - Ingress
  ingress:
  - from:
      - namespaceSelector:
          matchLabels:
            name: default