- name: variables_example1
  hosts: testservers
  remote_user: root 
 
  tasks:
  - include_vars: vars.txt
  - name: print the vars into a text file on remote machines
    shell: echo "I have enrolled in {{ Course }} and i am currently learning {{ Technology }}" > /home/charan/include_vars_example.txt