- name: Install LAMP Stack
  hosts: testservers
  remote_user: root

  vars:
    apache_pkg: apache3
    apache_service: apache3
    mysql_pkg: mariadb-server
    mysql_service: mariadb
    php_pkgs:
      - php
      - php-mysql
    php_src: /home/charan/ansible_playbooks/index.php
    php_dest: /var/www/html/index.php
    welcome_page: /var/www/html/index.html

  tasks:
  - name: Run apt-update
    apt:
      update_cache: yes

  - name: Installing Apache
    apt:
      pkg: "{{ apache_pkg }}"
      state: present

  - name: Enable Apache service
    service:
      name: "{{ apache_service }}"
      enabled: yes
      state: started

  - name: Delete default welcome page
    file:
      path: "{{ welcome_page }}"
      state: absent
    notify:
      - restart apache2 service

  - name: Installing MySQL DB Community Edition
    apt:
      name: "{{ mysql_pkg }}"
      state: present

  - name: Enable MySQL service
    service:
      name: "{{ mysql_service }}"
      enabled: yes
      state: started

  - name: Install PHP
    apt:
      name: "{{ php_pkgs }}"
      state: present
    notify:
      - restart mysql service

  - name: Copy PHP file
    copy:
      src: "{{ php_src }}"
      dest: "{{ php_dest }}"
    notify:
      - restart apache2 service
      - restart mysql service

  handlers:
  - name: restart apache2 service
    service:
      name: "{{ apache_service }}"
      state: restarted

  - name: restart mysql service
    service:
      name: "{{ mysql_service }}"
      state: restarted
