- name: var_file_example
  hosts: testservers
  remote_user: root 
  vars_files:
  - vars.txt

  tasks:
  - name: print the vars into a text file on remote machines
    shell: echo "I have enrolled in {{ Course }} and i am currently learning {{ Technology }}" > /home/charan/var_file_example.txt